common: &common
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']

development:
  <<: *common
  bucket: 'com.gunnertech.development.thebestthingintheworld'

test:
  <<: *common
  bucket: 'com.gunnertech.test.thebestthingintheworld'

staging:
  <<: *common
  bucket: 'com.gunnertech.staging.thebestthingintheworld'

production:
  <<: *common
  bucket: 'com.gunnertech.production.thebestthingintheworld'