require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MatchupsController do

  # This should return the minimal set of attributes required to create a valid
  # Matchup. As you add validations to Matchup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "thing_1" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MatchupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all matchups as @matchups" do
      matchup = Matchup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:matchups).should eq([matchup])
    end
  end

  describe "GET show" do
    it "assigns the requested matchup as @matchup" do
      matchup = Matchup.create! valid_attributes
      get :show, {:id => matchup.to_param}, valid_session
      assigns(:matchup).should eq(matchup)
    end
  end

  describe "GET new" do
    it "assigns a new matchup as @matchup" do
      get :new, {}, valid_session
      assigns(:matchup).should be_a_new(Matchup)
    end
  end

  describe "GET edit" do
    it "assigns the requested matchup as @matchup" do
      matchup = Matchup.create! valid_attributes
      get :edit, {:id => matchup.to_param}, valid_session
      assigns(:matchup).should eq(matchup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Matchup" do
        expect {
          post :create, {:matchup => valid_attributes}, valid_session
        }.to change(Matchup, :count).by(1)
      end

      it "assigns a newly created matchup as @matchup" do
        post :create, {:matchup => valid_attributes}, valid_session
        assigns(:matchup).should be_a(Matchup)
        assigns(:matchup).should be_persisted
      end

      it "redirects to the created matchup" do
        post :create, {:matchup => valid_attributes}, valid_session
        response.should redirect_to(Matchup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved matchup as @matchup" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matchup.any_instance.stub(:save).and_return(false)
        post :create, {:matchup => { "thing_1" => "invalid value" }}, valid_session
        assigns(:matchup).should be_a_new(Matchup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Matchup.any_instance.stub(:save).and_return(false)
        post :create, {:matchup => { "thing_1" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested matchup" do
        matchup = Matchup.create! valid_attributes
        # Assuming there are no other matchups in the database, this
        # specifies that the Matchup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Matchup.any_instance.should_receive(:update_attributes).with({ "thing_1" => "" })
        put :update, {:id => matchup.to_param, :matchup => { "thing_1" => "" }}, valid_session
      end

      it "assigns the requested matchup as @matchup" do
        matchup = Matchup.create! valid_attributes
        put :update, {:id => matchup.to_param, :matchup => valid_attributes}, valid_session
        assigns(:matchup).should eq(matchup)
      end

      it "redirects to the matchup" do
        matchup = Matchup.create! valid_attributes
        put :update, {:id => matchup.to_param, :matchup => valid_attributes}, valid_session
        response.should redirect_to(matchup)
      end
    end

    describe "with invalid params" do
      it "assigns the matchup as @matchup" do
        matchup = Matchup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Matchup.any_instance.stub(:save).and_return(false)
        put :update, {:id => matchup.to_param, :matchup => { "thing_1" => "invalid value" }}, valid_session
        assigns(:matchup).should eq(matchup)
      end

      it "re-renders the 'edit' template" do
        matchup = Matchup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Matchup.any_instance.stub(:save).and_return(false)
        put :update, {:id => matchup.to_param, :matchup => { "thing_1" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested matchup" do
      matchup = Matchup.create! valid_attributes
      expect {
        delete :destroy, {:id => matchup.to_param}, valid_session
      }.to change(Matchup, :count).by(-1)
    end

    it "redirects to the matchups list" do
      matchup = Matchup.create! valid_attributes
      delete :destroy, {:id => matchup.to_param}, valid_session
      response.should redirect_to(matchups_url)
    end
  end

end
