require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PickedMatchupsController do

  # This should return the minimal set of attributes required to create a valid
  # PickedMatchup. As you add validations to PickedMatchup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "matchup" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PickedMatchupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all picked_matchups as @picked_matchups" do
      picked_matchup = PickedMatchup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:picked_matchups).should eq([picked_matchup])
    end
  end

  describe "GET show" do
    it "assigns the requested picked_matchup as @picked_matchup" do
      picked_matchup = PickedMatchup.create! valid_attributes
      get :show, {:id => picked_matchup.to_param}, valid_session
      assigns(:picked_matchup).should eq(picked_matchup)
    end
  end

  describe "GET new" do
    it "assigns a new picked_matchup as @picked_matchup" do
      get :new, {}, valid_session
      assigns(:picked_matchup).should be_a_new(PickedMatchup)
    end
  end

  describe "GET edit" do
    it "assigns the requested picked_matchup as @picked_matchup" do
      picked_matchup = PickedMatchup.create! valid_attributes
      get :edit, {:id => picked_matchup.to_param}, valid_session
      assigns(:picked_matchup).should eq(picked_matchup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PickedMatchup" do
        expect {
          post :create, {:picked_matchup => valid_attributes}, valid_session
        }.to change(PickedMatchup, :count).by(1)
      end

      it "assigns a newly created picked_matchup as @picked_matchup" do
        post :create, {:picked_matchup => valid_attributes}, valid_session
        assigns(:picked_matchup).should be_a(PickedMatchup)
        assigns(:picked_matchup).should be_persisted
      end

      it "redirects to the created picked_matchup" do
        post :create, {:picked_matchup => valid_attributes}, valid_session
        response.should redirect_to(PickedMatchup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved picked_matchup as @picked_matchup" do
        # Trigger the behavior that occurs when invalid params are submitted
        PickedMatchup.any_instance.stub(:save).and_return(false)
        post :create, {:picked_matchup => { "matchup" => "invalid value" }}, valid_session
        assigns(:picked_matchup).should be_a_new(PickedMatchup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PickedMatchup.any_instance.stub(:save).and_return(false)
        post :create, {:picked_matchup => { "matchup" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested picked_matchup" do
        picked_matchup = PickedMatchup.create! valid_attributes
        # Assuming there are no other picked_matchups in the database, this
        # specifies that the PickedMatchup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PickedMatchup.any_instance.should_receive(:update_attributes).with({ "matchup" => "" })
        put :update, {:id => picked_matchup.to_param, :picked_matchup => { "matchup" => "" }}, valid_session
      end

      it "assigns the requested picked_matchup as @picked_matchup" do
        picked_matchup = PickedMatchup.create! valid_attributes
        put :update, {:id => picked_matchup.to_param, :picked_matchup => valid_attributes}, valid_session
        assigns(:picked_matchup).should eq(picked_matchup)
      end

      it "redirects to the picked_matchup" do
        picked_matchup = PickedMatchup.create! valid_attributes
        put :update, {:id => picked_matchup.to_param, :picked_matchup => valid_attributes}, valid_session
        response.should redirect_to(picked_matchup)
      end
    end

    describe "with invalid params" do
      it "assigns the picked_matchup as @picked_matchup" do
        picked_matchup = PickedMatchup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PickedMatchup.any_instance.stub(:save).and_return(false)
        put :update, {:id => picked_matchup.to_param, :picked_matchup => { "matchup" => "invalid value" }}, valid_session
        assigns(:picked_matchup).should eq(picked_matchup)
      end

      it "re-renders the 'edit' template" do
        picked_matchup = PickedMatchup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PickedMatchup.any_instance.stub(:save).and_return(false)
        put :update, {:id => picked_matchup.to_param, :picked_matchup => { "matchup" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested picked_matchup" do
      picked_matchup = PickedMatchup.create! valid_attributes
      expect {
        delete :destroy, {:id => picked_matchup.to_param}, valid_session
      }.to change(PickedMatchup, :count).by(-1)
    end

    it "redirects to the picked_matchups list" do
      picked_matchup = PickedMatchup.create! valid_attributes
      delete :destroy, {:id => picked_matchup.to_param}, valid_session
      response.should redirect_to(picked_matchups_url)
    end
  end

end
